In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("friends_info.csv")

In [3]:
df

              Name     Regd.no   Age   YoG
0          G.Rahul  2024106242    20  2028
1          A.Vinay  2024041712    19  2028
2  R.S.S Devadatta  2024012345    19  2028
3  M.Hemanth Kumar  2024088563    21  2028

In [4]:
df.isnull()

    Name   Regd.no    Age    YoG
0  False     False  False  False
1  False     False  False  False
2  False     False  False  False
3  False     False  False  False

In [5]:
df.isnull().sum()

Name        0
 Regd.no    0
 Age        0
 YoG        0
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      4 non-null      object
 1    Regd.no  4 non-null      int64
 2    Age      4 non-null      int64
 3    YoG      4 non-null      int64
dtypes: int64(3), object(1)
memory usage: 260.0+ bytes

In [7]:
df.describe()

            Regd.no        Age     YoG
count  4.000000e+00   4.000000     4.0
mean   2.024062e+09  19.750000  2028.0
std    4.297280e+04   0.957427     0.0
min    2.024012e+09  19.000000  2028.0
25%    2.024034e+09  19.000000  2028.0
50%    2.024065e+09  19.500000  2028.0
75%    2.024093e+09  20.250000  2028.0
max    2.024106e+09  21.000000  2028.0